// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6aQWcE0Qadr31PViPoXiRc2WLRwpUIgQ',
    appId: '1:819273820697:web:c713325562f03b5582d888',
    messagingSenderId: '819273820697',
    projectId: 'sapna-abc',
    authDomain: 'sapna-abc.firebaseapp.com',
    storageBucket: 'sapna-abc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj5_Ez9DNzw6sEsyHo_cdWbTuHDAQ3iWY',
    appId: '1:819273820697:android:1d2eb97e5e798eff82d888',
    messagingSenderId: '819273820697',
    projectId: 'sapna-abc',
    storageBucket: 'sapna-abc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChOqE0KyN8xxhfrYs2AXyzMdQze8NfHG4',
    appId: '1:819273820697:ios:1810916d24df0e5382d888',
    messagingSenderId: '819273820697',
    projectId: 'sapna-abc',
    storageBucket: 'sapna-abc.firebasestorage.app',
    iosBundleId: 'com.example.sapna',
  );
}
