name: Flutter CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # ✅ Dart 3.7.2 included
          channel: 'stable'

      - name: Check Flutter and Dart version
        run: flutter --version

      - name: Clean project
        run: flutter clean

      - name: Cache Pub dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project
        continue-on-error: true
        run: flutter analyze > analyze_report.txt

      - name: Upload analyze report
        uses: actions/upload-artifact@v4
        with:
          name: analyze_report
          path: analyze_report.txt

      - name: Run tests
        continue-on-error: true
        run: flutter test > test_report.txt

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test_report
          path: test_report.txt

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload the APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
