name: Flutter CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # 3. Clean project
      - name: Clean project
        run: flutter clean

      # 4. Cache Pub dependencies
      - name: Cache Pub dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}}
          restore-keys: |
            ${{ runner.os }}-pub-

      # 5. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 6. Analyze project
      - name: Analyze project
        continue-on-error: true
        run: flutter analyze > analyze_report.txt

      # 7. Upload analyze report
      - name: Upload analyze report
        uses: actions/upload-artifact@v4
        with:
          name: analyze_report
          path: analyze_report.txt

      # 8. Run tests
      - name: Run tests
        continue-on-error: true
        run: flutter test > test_report.txt 2>&1

      # 9. Upload test report
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test_report
          path: test_report.txt

      # 10. Build debug APK with verbose output
      - name: Build debug APK
        id: debug_build
        continue-on-error: true
        run: flutter build apk --debug -v > debug_report.txt 2>&1

      # 11. Upload debug report
      - name: Upload debug report
        uses: actions/upload-artifact@v4
        with:
          name: debug_report
          path: debug_report.txt

      # 12. Build release APK
      - name: Build release APK
        run: flutter build apk --release -v 2>&1 | tee release_report.txt

      # 13. Upload release report
      - name: Upload release report
        uses: actions/upload-artifact@v4
        with:
          name: release_report
          path: release_report.txt

      # 14. Upload the release APK
      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
